# Generated by Django 2.2 on 2019-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_movies',
            field=models.TextField(default='[]'),
        ),
    ]
