# Generated by Django 2.2 on 2019-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_focus_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(max_length=32, unique=True)),
                ('movie_title', models.TextField(default='')),
                ('movie_genres', models.TextField(default='')),
            ],
        ),
    ]
