# Generated by Django 2.2 on 2019-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_movieslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieslist',
            name='movie_id',
        ),
    ]
